Do change
daringLYL/angularToDo pull request #2
Opened 2019-07-24 15:31 UTC by daringLYL

我把文档里的双引号都改成了单引号，把IF里的==改成了===

2019-07-24 15:39 UTC, n8659150 requested changes
以后记得先checkout 到 master branch 然后在新建你的branch，不然你的commits会包含你之前所在的branch的commits

2019-07-24 15:39 UTC, n8659150 commented on will_to_do.js
> +var app = angular.module('exercise', ['ngStorage']);
不要用var， 这里用const

2019-07-24 15:40 UTC, n8659150 commented on will_to_do.js
>          var keycode = window.event ? e.keyCode : e.which;
这个判断有什么意义？

2019-07-24 15:41 UTC, n8659150 commented on will_to_do.js
> +app.controller('doExercise', function ($scope,$localStorage,$sessionStorage) {
$sessionStorage 没有用到，删掉

2019-07-24 15:42 UTC, n8659150 commented on will_to_do.js
>      $scope.dele = function(item){
dele是什么？改成delete，以后不要出现无意义的命名，也不要出现缩写。一共就几个字母，没必要缩写

2019-07-24 15:44 UTC, n8659150 commented on will_to_do.js
> +                if(item === $scope.$storage.result[index].name){
这个判断是没必要的，angular的ng-repeat里面，你点在哪个item上面，就可以获取到这个item的index，不用再通过匹配它的name来判断要删除哪个。
如果我建两个相同名字的item的话，这边就会获取到2个index，会一下子把两个相同名字的item都删掉。

2019-07-24 15:45 UTC, n8659150 requested changes
根据我的留言改一下

2019-07-25 13:05 UTC, daringLYL commented on will_to_do.js
>          var keycode = window.event ? e.keyCode : e.which;
我也不知道，这个是你写的。好像不写就无法执行

2019-07-25 14:56 UTC, n8659150 commented on will_to_do.js
>          var keycode = window.event ? e.keyCode : e.which;
这个不是我写的。

2019-07-25 14:57 UTC, n8659150 commented
新发的PR已经包含这些改动了，这个PR我关掉了

2019-07-25 14:57 UTC, closed without merging